- buf/registry/module/v1beta1/branch.proto
- buf/registry/module/v1beta1/branch_service.proto
- buf/registry/module/v1beta1/commit.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/module.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/module/v1beta1/resource.proto
- buf/registry/module/v1beta1/tag.proto
- buf/registry/module/v1beta1/tag_service.proto
- buf/registry/module/v1beta1/vcs_commit.proto
- buf/registry/module/v1beta1/vcs_commit_service.proto
- buf/registry/owner/v1beta1/organization.proto
- buf/registry/owner/v1beta1/organization_service.proto
- buf/registry/owner/v1beta1/owner.proto
- buf/registry/owner/v1beta1/owner_service.proto
- buf/registry/owner/v1beta1/user.proto
- buf/registry/owner/v1beta1/user_service.proto
- buf/registry/priv/extension/v1beta1/extension.proto
- buf/registry/storage/v1beta1/storage.proto
In order to ensure that all generated code comes from the correct package, add the go_package option (similar to protovalidate) to all .proto files.
This should also serve as a reminder for users that generated registry code should come from generated SDKs.
> Add go_package

- buf/registry/module/v1beta1/module_service.proto
- buf/registry/module/v1beta1/tag.proto
- buf/registry/module/v1beta1/tag_service.proto
- buf/registry/module/v1beta1/vcs_commit.proto
All fields that end in `_id` except `spdx_license_id` are UUIDs to my knowledge and should use `string.uuid` instead of `string.max_len` for validation.
> Fix *_id fields to use uuid validator

- buf/registry/module/v1beta1/branch.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/module.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/module/v1beta1/resource.proto
- buf/registry/module/v1beta1/tag.proto
- buf/registry/module/v1beta1/tag_service.proto
- buf/registry/owner/v1beta1/organization.proto
- buf/registry/owner/v1beta1/organization_service.proto
- buf/registry/owner/v1beta1/user.proto
- buf/registry/owner/v1beta1/user_service.proto
This regards the following limits:
* Metadata descriptions, on users, organizations, and modules;
* Branch names
* Tag names
Other validation rules have a less-trivial path forward, as they either do not have exactly-defined limits or they have limits that are not statically known, and thus may require us to relax validation in the public BSR to unify across the board.
> Adjust limits for trivial cases where v1alpha1 already has a defined, static limit

- buf/registry/owner/v1beta1/organization.proto
- buf/registry/owner/v1beta1/user.proto
Document the uniqueness of the `name` field on the field itself.
Closes https://github.com/bufbuild/registry-proto/issues/2
> Document uniqueness of `name` on `Organization` and `User`

- buf/registry/module/v1beta1/commit_service.proto
This replaces #17 as #16 was closed.
This removes the sending of `buf.yaml` and `buf.lock` files over the wire, and consequently these being part of the structure of `Modules` as we know them, instead sending over the specific information we need on the backend in a structured manner.
This fully standardizes on the `Node` terminology. A `Node` is a pointer to some content, either on the request or response side. Within this API now, we have:
- `FileNode`: A pointer to file content.
- `CreateCommitRequest.ModuleNode` - A set of `FileNodes` and an associated `ModuleRef` that represents the content of a single `Module.`.
- `CreateCommitRequest.DepNode` - A set of pointers to dependencies, which are just the `commit_ids` of the dependencies and their associated `Digest` (for verification).
- …
> Remove buf.yaml and buf.lock as part of API by sending over structured module and dependency content

- buf/registry/module/v1beta1/branch_service.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/module/v1beta1/tag_service.proto
- buf/registry/module/v1beta1/vcs_commit_service.proto
- buf/registry/owner/v1beta1/organization_service.proto
- buf/registry/owner/v1beta1/owner_service.proto
- buf/registry/owner/v1beta1/user_service.proto
This PR adds `max_items` to `GetOwnersRequest`.
I think we should avoid unbounded repeated refs and have sane limits. If a client needs to resolve >250 IDs or names, they can hit the endpoint multiple times.
Although it's not a list endpoint, used 250 for parity.
> Add max limit for refs or values in requests

- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/storage/v1beta1/storage.proto
* Rejects paths with backslashes
* Limits length to 4096 (will be enforced in v1alpha1 as well.)
* Enforces relative paths (no preceding slash.)
* Enforces no trailing slash
* Enforces normalized paths (no . or .. elements)
Regular expression breakdown:
```
Path := PathSegment(/PathSegment)*
PathSegment := [^/.][^/]?|[^/][^/.]|[^/]{3,}
```
* `Path` enforces normalized, relative paths by ensuring that there is one or more path segments with one and only one `/` between them and nowhere else.
* `PathSegment` enforces each path segment can't be `.` or `..` and must be non-empty. It does this by matching any 1 character segment that isn't `.`, any 2 character segment that isn't `..`, and any 3 character segment.
Overall path length is then enforced with `max_len` and Windows-style paths are …
> Validation for paths

- buf/registry/module/v1beta1/module_service.proto
- buf/registry/owner/v1beta1/organization_service.proto
- buf/registry/owner/v1beta1/user.proto
- buf/registry/owner/v1beta1/user_service.proto
This PR removes `UserServerRole` in its entirety from the API surface. Putting this up for review/feedback, although need to think about this.
I'd go as far as removing the "special" handling of empty refs in the 3 endpoints and adding limits like other endpoints.
- ListModulesRequest
- ListOrganizationsRequest
- ListUsersRequest
Having the `UserServerRole` be a core primitive in the API is a potential footgun because in various places we're going to have conditional checks to expose, hide, or mask this field. Which may leak users with elevated privileges.
It feels there should be a dedicated `AdminService` either in the registry API or even better, an internal set of protos that aren't widely publicized. It'll be less error-prone to secure a whole service or RPC than an individual field.
> Remove UserServerRole

- buf/registry/module/v1beta1/resource.proto
When building these objects, you sometimes have an empty value for `ref`, but know that you only have a `ref`, and you want to not have to write a lot of code to do empty string checking. IMO we should just document that empty is the same as null.
> Document ResourceRef.ref to have equivalent behavior regardless of presence

- buf/registry/module/v1beta1/branch.proto
- buf/registry/module/v1beta1/module.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/module/v1beta1/resource.proto
- buf/registry/module/v1beta1/tag.proto
- buf/registry/module/v1beta1/vcs_commit.proto
This matches the newly-unified v1alpha1 limits.
`required` does not seem to be necessary when `min_len` is present.
> Adjust validation for module name length

- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/resource.proto
- buf/registry/module/v1beta1/vcs_commit.proto
We currently only support Git SHA1 hashes and nothing else. In the future, adding a union to this regex could allow more hash shapes for different VCSes or different Git repository digests.
> Adjust validation for VCS Commit Hash

- buf/registry/module/v1beta1/branch_service.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/resource.proto
- buf/registry/module/v1beta1/tag_service.proto
- buf/registry/module/v1beta1/vcs_commit_service.proto
@saquibmian context:
Buckle up, here we go!
First, a `Digest` uniquely identifies the content it closes over. Here's how we get to this conclusion:
1. Every `Commit` has a set of `Digests`.
- For `Digest`s of type shake256 -- which is the `Digest` we write in lock files today -- this includes:
- all protos (file and path)
- `buf.yaml` (or other config file)
- `buf.lock`
- the single documentation file path
- license file and path
- For `Digests` of type b3, this includes:
- all protos 
- dependencies (module identity and commit name)
- the single documentation file and path
- license file and path
- breaking and lint configs
- We will refer to the content that the digest closes over as `Content`.
2. Two `Commit`s with identical `Content` (i.e., config, files, and dependencies) will …
> Make Digest a first-class citizen

- buf/registry/module/v1beta1/commit_service.proto
Blobs are not globally addressable across the BSR, largely for SOC2 compliance so that we can safely and cheaply delete all assets for a repository. Blobs are scoped to a repository.
Therefore, when we query for missing blobs, we have to query for missing blobs in the context of a `ModuleRef`. I chose to take the route of querying for multiple sets of module blobs in a single request rather than one request per set of module blobs.
> Fix missing blobs request/response

- buf/registry/module/v1beta1/branch_service.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/module/v1beta1/tag_service.proto
- buf/registry/module/v1beta1/vcs_commit_service.proto
- buf/registry/owner/v1beta1/organization_service.proto
- buf/registry/owner/v1beta1/user_service.proto
We wanted to either pick some arbitrary large value or remove it entirely. Others pointed out that 255 is short enough that it might be a bit too small for base64'd cursor pagination, so I picked 4096 as an arbitrary value.
The justification for this is that _removing_ validation later would be backwards compatible, but adding validation later would be backwards incompatible. So a lenient limit seems like a decent idea.
I think this is the last of the validation issues. I made a couple additional passes to make sure and didn't see anything else that obviously needed attention.
> Adjust page token validation

- buf/registry/module/v1beta1/module.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/owner/v1beta1/organization.proto
- buf/registry/owner/v1beta1/organization_service.proto
- buf/registry/owner/v1beta1/user.proto
- buf/registry/owner/v1beta1/user_service.proto
Adds to all uri fields that can be optional set. Using with options still adds ignore_empty to allow unsetting the value.
Otherwise empty string "" will fail validation with: 
```
invalid_argument: validation error:
- values[0].url: value must be a valid URI [string.uri]
```
> Add ignore_empty for optional uri field validation

- buf/registry/owner/v1beta1/user.proto
Follows the nomenclature in the docs of a bot user over machine. Renames the type and adds small docs strings.
> Rename user type MACHINE to BOT

- buf/registry/owner/v1beta1/user_service.proto
Took a stab at improving the comments around the `DeleteUsers` behavior.
@emcfarlane does this make sense in terms of the implementation?
- Duplicate ids or names are deduplicated, and only one user will be deleted
- Duplicate refs that belong to the same user, id and name, are deduplicated and only one user is deleted
- Both scenarios are allowed and do not surface an error
> Document DeleteUsers behavior

- buf/registry/owner/v1beta1/user_service.proto
To allow unsetting the URL we must allow validation to pass on an empty string. New protovalidate [behaviour](https://github.com/bufbuild/protovalidate-go/pull/76) changes optional fields with an `ignore_empty` set to act as a no-op. Fallback to a CEL expression to validate the URL if present.
> Fix UserService/PatchUsers URL validation

- buf/registry/owner/v1beta1/organization.proto
- buf/registry/owner/v1beta1/organization_service.proto
- buf/registry/owner/v1beta1/owner.proto
- buf/registry/owner/v1beta1/user.proto
- buf/registry/owner/v1beta1/user_service.proto
Adds a regex pattern match for usernames "^[a-z][a-z0-9-]*[a-z0-9]$". Must start with a lowercase letter, only consist of alpha numerics or hypens and doesn't end with a hypen. Bumped the min length to 2 as the RE2 syntax doesn't support lookback syntax.
Error on failure will be:
```
validation failed: validation error:
- name: value does not match regex pattern `^[a-z][a-z0-9-]*[a-z0-9]$` [string.pattern]
```
Should we instead use a CEL expression for better errors?
```proto
(buf.validate.field).cel = {
id: "username",
message: "value must start with a lowercase letter and contain only letters, numbers, or hypens and cannot end with a hypen",
expression: "this.matches('^[a-z][a-z0-9-]*[a-z0-9]$')"
}
```
```
validation failed: validation error:
- name: value must start with a lowercase …
```
> Add username validation for names

- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/owner/v1beta1/user_service.proto
Adds two new filtering options for `UserService/ListRequestUsers`:
- `has_types`: only return users of types.
- `has_states`: only return users of states.
Required behaviour for API consumers.
> Add filtering options for ListRequestUsers

- Makefile
- buf/registry/module/v1beta1/branch.proto
- buf/registry/module/v1beta1/branch_service.proto
- buf/registry/module/v1beta1/commit_service.proto
There are two things going on in this PR:
1. `CreateCommits` is updated so that it simply creates Commits for Modules without pushing them onto any Branch or assigning any Tags to them. 
- The idea is that Commits can be "uploaded" to the BSR before they are placed in their correct places in Branch history or assigned Tags. This is very useful for `sync`, where potentially 1000s of Commits need to be created before pushing them on a Branch. Because Branch history should be patched atomically and with a lock, creating Commits in-band becomes untenable.
- These Commits can only be referenced by their `ID`, `Digest`, or a `VCSCommitRef` if there was any `AssociatedVCSCommit`.
2. Two new RPCs are added to mutate a `Branch`'s history: `BranchService.Push` and `BranchService.Rebase`.
- `Push` …
> Revamp CreateCommits to just create Commits and add specialized Push and Rebase endpoints

- buf/registry/owner/v1beta1/user_service.proto
Invalid field validation for lists. Fix the validation syntax to use the `repeated` selector. Also added a `unique` constraint as for filtering only unique values should be present.
> Fix owners ListUsers request validations

- buf/registry/module/v1beta1/download_service.proto
Fixes the docs on the Download method by removing the note to a non existent field reference: `include_dep_files`.
> Remove note on Download for include_dep_files

- buf/registry/module/v1beta1/label_service.proto
Removed TODO on ListLabelsHistoryRequest because we definitely want the default to be descending. That is the common use case, and we just had [an actual bug](https://github.com/bufbuild/core/pull/13621) in the BSR because the default didn't do something useful in the v1alpha1 equivalent of this API.
> Default to descending order for ListLabels and ListLabelsHistory

- buf/registry/legacy/federation/v1beta1/doc.proto
- buf/registry/legacy/federation/v1beta1/graph.proto
- buf/registry/legacy/federation/v1beta1/graph_service.proto
- buf/registry/legacy/federation/v1beta1/resource.proto
- buf/registry/legacy/federation/v1beta1/upload_service.proto
- buf/registry/module/v1beta1/graph.proto
This adds the `buf.registry.legacy.federation.v1beta1` package.
We need to support legacy federation for a few of our early customers, and this is the easiest way for us to do so. It effectively means supporting federation on two endpoints: `GetGraph` and `Upload`. The edits to these endpoints and their associated types will mean an API that is sufficiently different and unclean that we instead are splitting these out into their own package (and associated endpoints).
> Add buf.registry.legacy.federation.v1beta1 package

- buf/registry/module/v1beta1/label_service.proto
Add the constraint of newer commit `create_time` timestamps when updated a Label pointer.
> Update CreateOrUpdateLabel RPC docs

- buf/registry/legacy/federation/v1beta1/graph.proto
- buf/registry/legacy/federation/v1beta1/resource.proto
- buf/registry/legacy/federation/v1beta1/upload_service.proto
Protovalidate doesn't yet have a rule that covers what we need for the registry field. We internally rely on the field being allowed to contain an address with a port, not just a hostname; while protovalidate does have an address validator that allows either an IP or a hostname, it lacks an address with optional port validator. Rather than try to write a complicated regular expression, I think it's best to just allow the field to contain any string, which will eventually be validated implicitly by trying to use it as an address anyways.
> Make registry field more lenient

- buf/registry/legacy/federation/v1beta1/graph.proto
Add UUID field validation for type `buf.registry.legacy.federation.v1beta1.Graph.Node` field `commit_id`.
> Add UUID validation to legacy graph service commit_id

- buf/registry/legacy/federation/v1beta1/upload_service.proto
- buf/registry/module/v1beta1/download_service.proto
- buf/registry/module/v1beta1/upload_service.proto
This PR's primary purpose is to remove the need to specify dependencies between Contents on Upload, and to move external dependencies to the top-level of the UploadRequest. We do not need to manually specify dependencies between Contents, as this is implicitly done via .proto imports. We also want to make sure that for a given set of Contents, there is exactly one dependency Commit ID for a given Module. This matches what we have in Workspaces. The API will no longer enable uploading multiple Workspaces in one RPC, but we see no use case for this.
This PR also moves DigestType to the top-level of DownloadRequest, to match the other RPCs.
> Move DepRefs and DigestType to top-level

- buf/registry/module/v1/label_service.proto
- buf/registry/module/v1beta1/label_service.proto
To view a diff for a commit on a label we need to be able to get the previous commit on that label. Added `start_commit_id` so we can fetch the history starting at the desired commit and using a page size of 2 can also get the previous commit.
> Add start_commit_id to ListLabelHistoryRequest

- buf/registry/module/v1/label_service.proto
Field number 5 was inadvertently skipped in https://github.com/bufbuild/registry-proto/pull/80
> Fix field numbers for v1 ListLabelHistoryRequest

- .github/workflows/buf.yaml
This will allow https://github.com/bufbuild/registry-proto/pull/84 to get pushed. Will revert this change once it is pushed.
> Allow push even with breaking change

- .github/workflows/buf.yaml
This reverts commit c0a5c7982e1f4c0935d031d1c18a166bb57a4774 so breaking changes block push again.
> Revert "Allow push even with breaking change (#85)"

- buf/registry/module/v1/label_service.proto
- buf/registry/module/v1beta1/label_service.proto
This will make it possible to fetch only the commits on a label where the module content actually changed.
> Add only_content_changes to ListLabelHistoryRequest

- buf/registry/module/v1/commit_service.proto
- buf/registry/module/v1/label_service.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/label_service.proto
This is more useful today. Any client that cares about case sensitivity can post-process the returned results.
> Document that query parameters are case-insensitive

- .github/workflows/buf.yaml
- buf/registry/module/v1/commit_service.proto
- buf/registry/module/v1/label_service.proto
- buf/registry/module/v1/module_service.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/label_service.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/owner/v1/organization_service.proto
- buf/registry/owner/v1/user_service.proto
This resolves 2 kinds of TODOs:
1. Defaults ordering to DESC instead of ASC for create time. In the abstract, it is generally more useful to see things that have been created recently because recency is a proxy for relevance. In the frontend, we would more frequently want the recent items anyway (e.g. commits). GitHub REST API also defaults to DESC for timestamp fields. Either way this decision for a default is not a big deal, we should decide and remove the TODO.
2. It seems like we need to define the behavior of unspecified anyway so I don't see any value in explicitly setting the default value here. My proposal is to keep the default unset and just remove the TODO.
> Default to ORDER_CREATE_TIME_DESC

- buf/registry/module/v1/label.proto
- buf/registry/module/v1/label_service.proto
- buf/registry/module/v1/module.proto
- buf/registry/module/v1/resource.proto
- buf/registry/module/v1beta1/label.proto
- buf/registry/module/v1beta1/label_service.proto
- buf/registry/module/v1beta1/module.proto
- buf/registry/module/v1beta1/resource.proto
Behavior changes for archived labels:
1. Archived labels can be returned by any API.
2. Archived labels are now valid ResourceRefs.
3. Add explicit filter parameter to ListLabels so it can return only unarchived labels (the default), both archived and unarchived labels (needed by the UI), or only archived labels (could be useful for the future).
4. Add UnarchiveLabels RPC so the frontend can implement an "undo" button if someone accidentally archives a label (or wants to unarchive a label for any other reason).
> Change how archived labels work

- buf/registry/owner/v1/user.proto
This state exists in the backend so we are going to continue to support it.
> Remove TODO for USER_VERIFICATION_STATUS_OFFICIAL

- .github/workflows/buf.yaml
It was disabled so we could merge https://github.com/bufbuild/registry-proto/pull/95 and https://github.com/bufbuild/registry-proto/pull/92
> Enable breaking change detection on main branch

- buf/registry/module/v1/commit_service.proto
- buf/registry/module/v1beta1/commit_service.proto
A dashful UUID is 36 chars long.
> Fix length for `id_query`

- buf/registry/module/v1/commit_service.proto
- buf/registry/module/v1beta1/commit_service.proto
On the backend, we should effectively strip out dashes from the input and then do a case insensitive match against the dashless commit id.
For example:
id_query of `123-4` or `1234` should both match commits with ids that contain the any of the strings `1234`, `1-234`, `12-34`, `123-4`
> Document that id_query is dash insensitive

- buf/registry/module/v1/commit.proto
- buf/registry/module/v1/label.proto
- buf/registry/module/v1beta1/commit.proto
- buf/registry/module/v1beta1/label.proto
Users can get deleted. This is consistent with the behavior already documented for Commit.created_by_user_id
https://github.com/bufbuild/registry-proto/blob/5a40a3fc390ac8316ca34c7776aa2f118be288b4/buf/registry/module/v1/commit.proto#L62-L65
> Update Label.updated_by_user_id to be not required

- buf/registry/module/v1/module_service.proto
- buf/registry/module/v1beta1/module_service.proto
If present, it must be non-empty and may not point to an archived label.
> Fix documentation and validation on `UpdateModulesRequest.default_label_name`

- buf/registry/module/v1/commit_service.proto
- buf/registry/module/v1/label_service.proto
- buf/registry/module/v1beta1/commit_service.proto
- buf/registry/module/v1beta1/label_service.proto
The documentation on ResourceRef for both List{Commits,Labels} is phrased in a way that could be confused to mean the endpoint always returns the specified results, but that doesn't make sense because there are additional filtering fields on each of these RPCs.
This PR updates the documentation to clarify that filter fields are additive (i.e. ANDed together) to the resource_ref filter.
Slack discussion: https://bufprivate.slack.com/archives/C02KXVDB23B/p1717182975280679
> Clarify that filters are additive

- .github/CODEOWNERS
Currently, the owner role on the first line is overwritten the second line, this PR fixes that.
From [GitHub's docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file):
> Order is important; the last matching pattern takes the most precedence.
> Fix code owner rule that got overwritten

- buf.yaml
Fixes the lint warning when running `make`
> WARN    Category DEFAULT referenced in your buf.yaml is deprecated. It has been replaced by category STANDARD.
> Update deprecated lint category

- buf/registry/plugin/v1beta1/resource_service.proto
This adds the `ResourceService` for the `buf.registry.plugin.v1beta1` Plugins package. Follows the service implementation in [Modules](https://github.com/bufbuild/registry-proto/pull/70). See https://github.com/bufbuild/registry-proto/pull/132
> Add ResourceService for v1beta1 Plugins

- buf/registry/module/v1/commit_service.proto
- buf/registry/plugin/v1beta1/check_service.proto
This PR adds a `CheckService` that takes a`ResourceRef` to allow API callers to fetch rules/categories for a plugin (latest commit on default label), label (latest commit) or commit.
For a moment, I thought _just maybe_ we could ask callers to download the wasm blob and invoke it instead, but I suspect we're not there yet. We need some way to get the rules/categories cheaply.
> Add CheckService to plugin.v1beta1

- buf/registry/module/v1/label_service.proto
- buf/registry/module/v1beta1/label_service.proto
- buf/registry/plugin/v1beta1/label_service.proto
This fixes a typo for the non existant type CommitDigest and replaces it with Label.
> Fix list resources by CommitDigest to Label

- buf/registry/plugin/v1beta1/commit.proto
- buf/registry/plugin/v1beta1/commit_service.proto
- buf/registry/plugin/v1beta1/label_service.proto
- buf/registry/policy/v1beta1/commit.proto
- buf/registry/policy/v1beta1/commit_service.proto
- buf/registry/policy/v1beta1/digest.proto
- buf/registry/policy/v1beta1/label_service.proto
This adds digest support to policies, following on from modules and plugins. The digest type for policies is O1.
> Add Digests to Policies

- buf/registry/policy/v1beta1/upload_service.proto
Allow setting a scoped label ref when pushing a policy, [same way we do for plugins](https://github.com/bufbuild/registry-proto/blob/e1da6b5587047ca76e5c3de95e750eb7d1bef531/buf/registry/plugin/v1beta1/upload_service.proto#L50-L60).
> Use policy scoped label ref

- buf/registry/module/v1/module_service.proto
- buf/registry/module/v1beta1/module_service.proto
- buf/registry/owner/v1/organization_service.proto
- buf/registry/plugin/v1beta1/plugin_service.proto
Fix for [this comment](https://github.com/bufbuild/registry-proto/pull/149#discussion_r2216655935), which still validates URI validity.
> Use `uri_or_empty` CEL rule for optional URIs

- buf/registry/plugin/v1beta1/label.proto
- buf/registry/plugin/v1beta1/label_service.proto
- buf/registry/policy/v1beta1/label_service.proto
Plugin and Policy labels are not protected via review flow, and these commits don't have review state. Only Module commits and labels have review flow.
> Plugin and Policy: Remove comments associated to review flow

- buf/registry/owner/v1/user_service.proto
Retrieves the currently authenticated user.
I haven't documented error codes as we tend not to do that, but an implementation might respond with:
* Unauthenticated if the request does not include authentication
* NotFound if authentication is included, but does not match to a user
* InvalidArgument if the authentication is invalid
* PermissionDenied if the user has been disabled or deactivated for some reason
For context, here's how v1alpha1 defines a similar RPC: https://github.com/bufbuild/buf/blob/7471eb6817e604885bd7632cd8472de8940bec48/proto/buf/alpha/registry/v1alpha1/authn.proto#L23-L28
> Add GetCurrentUser to v1 UserService
